# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_authentication_v1_user_info import IoK8sApiAuthenticationV1UserInfo  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiAuthenticationV1UserInfo(unittest.TestCase):
    """IoK8sApiAuthenticationV1UserInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAuthenticationV1UserInfo(self):
        """Test IoK8sApiAuthenticationV1UserInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_authentication_v1_user_info.IoK8sApiAuthenticationV1UserInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
