# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_networking_v1beta1_ingress_tls import IoK8sApiNetworkingV1beta1IngressTLS  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiNetworkingV1beta1IngressTLS(unittest.TestCase):
    """IoK8sApiNetworkingV1beta1IngressTLS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiNetworkingV1beta1IngressTLS(self):
        """Test IoK8sApiNetworkingV1beta1IngressTLS"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_networking_v1beta1_ingress_tls.IoK8sApiNetworkingV1beta1IngressTLS()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
