# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_batch_v1beta1_cron_job_list import IoK8sApiBatchV1beta1CronJobList  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiBatchV1beta1CronJobList(unittest.TestCase):
    """IoK8sApiBatchV1beta1CronJobList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiBatchV1beta1CronJobList(self):
        """Test IoK8sApiBatchV1beta1CronJobList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_batch_v1beta1_cron_job_list.IoK8sApiBatchV1beta1CronJobList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
