# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_storage_v1beta1_volume_error import IoK8sApiStorageV1beta1VolumeError  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiStorageV1beta1VolumeError(unittest.TestCase):
    """IoK8sApiStorageV1beta1VolumeError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiStorageV1beta1VolumeError(self):
        """Test IoK8sApiStorageV1beta1VolumeError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_storage_v1beta1_volume_error.IoK8sApiStorageV1beta1VolumeError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
