# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.api.storage_api import StorageApi  # noqa: E501
from argo_client.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = argo_client.api.storage_api.StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_storage_api_group(self):
        """Test case for get_storage_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
