# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_networking_v1_network_policy_egress_rule import IoK8sApiNetworkingV1NetworkPolicyEgressRule  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiNetworkingV1NetworkPolicyEgressRule(unittest.TestCase):
    """IoK8sApiNetworkingV1NetworkPolicyEgressRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiNetworkingV1NetworkPolicyEgressRule(self):
        """Test IoK8sApiNetworkingV1NetworkPolicyEgressRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_networking_v1_network_policy_egress_rule.IoK8sApiNetworkingV1NetworkPolicyEgressRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
