# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_core_v1_typed_local_object_reference import IoK8sApiCoreV1TypedLocalObjectReference  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiCoreV1TypedLocalObjectReference(unittest.TestCase):
    """IoK8sApiCoreV1TypedLocalObjectReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1TypedLocalObjectReference(self):
        """Test IoK8sApiCoreV1TypedLocalObjectReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_core_v1_typed_local_object_reference.IoK8sApiCoreV1TypedLocalObjectReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
