# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_apimachinery_pkg_api_resource_quantity import IoK8sApimachineryPkgApiResourceQuantity  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApimachineryPkgApiResourceQuantity(unittest.TestCase):
    """IoK8sApimachineryPkgApiResourceQuantity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApiResourceQuantity(self):
        """Test IoK8sApimachineryPkgApiResourceQuantity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_apimachinery_pkg_api_resource_quantity.IoK8sApimachineryPkgApiResourceQuantity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
