# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_settings_v1alpha1_pod_preset import IoK8sApiSettingsV1alpha1PodPreset  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiSettingsV1alpha1PodPreset(unittest.TestCase):
    """IoK8sApiSettingsV1alpha1PodPreset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiSettingsV1alpha1PodPreset(self):
        """Test IoK8sApiSettingsV1alpha1PodPreset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_settings_v1alpha1_pod_preset.IoK8sApiSettingsV1alpha1PodPreset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
