# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_apps_v1beta2_replica_set_spec import IoK8sApiAppsV1beta2ReplicaSetSpec  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiAppsV1beta2ReplicaSetSpec(unittest.TestCase):
    """IoK8sApiAppsV1beta2ReplicaSetSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAppsV1beta2ReplicaSetSpec(self):
        """Test IoK8sApiAppsV1beta2ReplicaSetSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_apps_v1beta2_replica_set_spec.IoK8sApiAppsV1beta2ReplicaSetSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
