# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1beta1_external_documentation import IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation(unittest.TestCase):
    """IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation(self):
        """Test IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1beta1_external_documentation.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
