# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_core_v1_volume_node_affinity import IoK8sApiCoreV1VolumeNodeAffinity  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiCoreV1VolumeNodeAffinity(unittest.TestCase):
    """IoK8sApiCoreV1VolumeNodeAffinity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1VolumeNodeAffinity(self):
        """Test IoK8sApiCoreV1VolumeNodeAffinity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_core_v1_volume_node_affinity.IoK8sApiCoreV1VolumeNodeAffinity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
