# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.models.io_k8s_api_autoscaling_v2beta2_external_metric_source import IoK8sApiAutoscalingV2beta2ExternalMetricSource  # noqa: E501
from argo_client.rest import ApiException


class TestIoK8sApiAutoscalingV2beta2ExternalMetricSource(unittest.TestCase):
    """IoK8sApiAutoscalingV2beta2ExternalMetricSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAutoscalingV2beta2ExternalMetricSource(self):
        """Test IoK8sApiAutoscalingV2beta2ExternalMetricSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo_client.models.io_k8s_api_autoscaling_v2beta2_external_metric_source.IoK8sApiAutoscalingV2beta2ExternalMetricSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
