# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.15.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import argo_client
from argo_client.api.storage_v1alpha1_api import StorageV1alpha1Api  # noqa: E501
from argo_client.rest import ApiException


class TestStorageV1alpha1Api(unittest.TestCase):
    """StorageV1alpha1Api unit test stubs"""

    def setUp(self):
        self.api = argo_client.api.storage_v1alpha1_api.StorageV1alpha1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_storage_v1alpha1_volume_attachment(self):
        """Test case for create_storage_v1alpha1_volume_attachment

        """
        pass

    def test_delete_storage_v1alpha1_collection_volume_attachment(self):
        """Test case for delete_storage_v1alpha1_collection_volume_attachment

        """
        pass

    def test_delete_storage_v1alpha1_volume_attachment(self):
        """Test case for delete_storage_v1alpha1_volume_attachment

        """
        pass

    def test_get_storage_v1alpha1_api_resources(self):
        """Test case for get_storage_v1alpha1_api_resources

        """
        pass

    def test_list_storage_v1alpha1_volume_attachment(self):
        """Test case for list_storage_v1alpha1_volume_attachment

        """
        pass

    def test_patch_storage_v1alpha1_volume_attachment(self):
        """Test case for patch_storage_v1alpha1_volume_attachment

        """
        pass

    def test_read_storage_v1alpha1_volume_attachment(self):
        """Test case for read_storage_v1alpha1_volume_attachment

        """
        pass

    def test_replace_storage_v1alpha1_volume_attachment(self):
        """Test case for replace_storage_v1alpha1_volume_attachment

        """
        pass

    def test_watch_storage_v1alpha1_volume_attachment(self):
        """Test case for watch_storage_v1alpha1_volume_attachment

        """
        pass

    def test_watch_storage_v1alpha1_volume_attachment_list(self):
        """Test case for watch_storage_v1alpha1_volume_attachment_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
