# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_storage_v1alpha1_volume_attachment import IoK8sApiStorageV1alpha1VolumeAttachment  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiStorageV1alpha1VolumeAttachment(unittest.TestCase):
    """IoK8sApiStorageV1alpha1VolumeAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiStorageV1alpha1VolumeAttachment(self):
        """Test IoK8sApiStorageV1alpha1VolumeAttachment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_storage_v1alpha1_volume_attachment.IoK8sApiStorageV1alpha1VolumeAttachment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
