# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from api.version_api import VersionApi  # noqa: E501
from argo.sdk.rest import ApiException


class TestVersionApi(unittest.TestCase):
    """VersionApi unit test stubs"""

    def setUp(self):
        self.api = api.version_api.VersionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_code_version(self):
        """Test case for get_code_version

        """
        pass


if __name__ == '__main__':
    unittest.main()
