# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from api.apis_api import ApisApi  # noqa: E501
from argo.sdk.rest import ApiException


class TestApisApi(unittest.TestCase):
    """ApisApi unit test stubs"""

    def setUp(self):
        self.api = api.apis_api.ApisApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_api_versions(self):
        """Test case for get_api_versions

        """
        pass


if __name__ == '__main__':
    unittest.main()
