# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_networking_v1_network_policy_ingress_rule import IoK8sApiNetworkingV1NetworkPolicyIngressRule  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiNetworkingV1NetworkPolicyIngressRule(unittest.TestCase):
    """IoK8sApiNetworkingV1NetworkPolicyIngressRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiNetworkingV1NetworkPolicyIngressRule(self):
        """Test IoK8sApiNetworkingV1NetworkPolicyIngressRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_networking_v1_network_policy_ingress_rule.IoK8sApiNetworkingV1NetworkPolicyIngressRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
