# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from api.authentication_api import AuthenticationApi  # noqa: E501
from argo.sdk.rest import ApiException


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = api.authentication_api.AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_authentication_api_group(self):
        """Test case for get_authentication_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
