# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_core_v1_config_map_env_source import IoK8sApiCoreV1ConfigMapEnvSource  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiCoreV1ConfigMapEnvSource(unittest.TestCase):
    """IoK8sApiCoreV1ConfigMapEnvSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1ConfigMapEnvSource(self):
        """Test IoK8sApiCoreV1ConfigMapEnvSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_core_v1_config_map_env_source.IoK8sApiCoreV1ConfigMapEnvSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
