# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_node_v1beta1_runtime_class import IoK8sApiNodeV1beta1RuntimeClass  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiNodeV1beta1RuntimeClass(unittest.TestCase):
    """IoK8sApiNodeV1beta1RuntimeClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiNodeV1beta1RuntimeClass(self):
        """Test IoK8sApiNodeV1beta1RuntimeClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_node_v1beta1_runtime_class.IoK8sApiNodeV1beta1RuntimeClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
