# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_rbac_v1beta1_role import IoK8sApiRbacV1beta1Role  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiRbacV1beta1Role(unittest.TestCase):
    """IoK8sApiRbacV1beta1Role unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiRbacV1beta1Role(self):
        """Test IoK8sApiRbacV1beta1Role"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_rbac_v1beta1_role.IoK8sApiRbacV1beta1Role()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
