# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_core_v1_binding import IoK8sApiCoreV1Binding  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiCoreV1Binding(unittest.TestCase):
    """IoK8sApiCoreV1Binding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1Binding(self):
        """Test IoK8sApiCoreV1Binding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_core_v1_binding.IoK8sApiCoreV1Binding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
