# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_apimachinery_pkg_apis_meta_v1_initializers import IoK8sApimachineryPkgApisMetaV1Initializers  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApimachineryPkgApisMetaV1Initializers(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1Initializers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1Initializers(self):
        """Test IoK8sApimachineryPkgApisMetaV1Initializers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_apimachinery_pkg_apis_meta_v1_initializers.IoK8sApimachineryPkgApisMetaV1Initializers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
