# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_node_v1alpha1_runtime_class_spec import IoK8sApiNodeV1alpha1RuntimeClassSpec  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiNodeV1alpha1RuntimeClassSpec(unittest.TestCase):
    """IoK8sApiNodeV1alpha1RuntimeClassSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiNodeV1alpha1RuntimeClassSpec(self):
        """Test IoK8sApiNodeV1alpha1RuntimeClassSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_node_v1alpha1_runtime_class_spec.IoK8sApiNodeV1alpha1RuntimeClassSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
