# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1beta1_api_service import IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService(unittest.TestCase):
    """IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService(self):
        """Test IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1beta1_api_service.IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
