# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1beta1_custom_resource_subresource_scale import IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale(unittest.TestCase):
    """IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale(self):
        """Test IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_apiextensions_apiserver_pkg_apis_apiextensions_v1beta1_custom_resource_subresource_scale.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
