# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_batch_v1beta1_cron_job_spec import IoK8sApiBatchV1beta1CronJobSpec  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiBatchV1beta1CronJobSpec(unittest.TestCase):
    """IoK8sApiBatchV1beta1CronJobSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiBatchV1beta1CronJobSpec(self):
        """Test IoK8sApiBatchV1beta1CronJobSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_batch_v1beta1_cron_job_spec.IoK8sApiBatchV1beta1CronJobSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
