# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_apimachinery_pkg_runtime_raw_extension import IoK8sApimachineryPkgRuntimeRawExtension  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApimachineryPkgRuntimeRawExtension(unittest.TestCase):
    """IoK8sApimachineryPkgRuntimeRawExtension unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgRuntimeRawExtension(self):
        """Test IoK8sApimachineryPkgRuntimeRawExtension"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_apimachinery_pkg_runtime_raw_extension.IoK8sApimachineryPkgRuntimeRawExtension()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
