# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_admissionregistration_v1beta1_service_reference import IoK8sApiAdmissionregistrationV1beta1ServiceReference  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiAdmissionregistrationV1beta1ServiceReference(unittest.TestCase):
    """IoK8sApiAdmissionregistrationV1beta1ServiceReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAdmissionregistrationV1beta1ServiceReference(self):
        """Test IoK8sApiAdmissionregistrationV1beta1ServiceReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_admissionregistration_v1beta1_service_reference.IoK8sApiAdmissionregistrationV1beta1ServiceReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
