# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_authorization_v1_subject_access_review_status import IoK8sApiAuthorizationV1SubjectAccessReviewStatus  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiAuthorizationV1SubjectAccessReviewStatus(unittest.TestCase):
    """IoK8sApiAuthorizationV1SubjectAccessReviewStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAuthorizationV1SubjectAccessReviewStatus(self):
        """Test IoK8sApiAuthorizationV1SubjectAccessReviewStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_authorization_v1_subject_access_review_status.IoK8sApiAuthorizationV1SubjectAccessReviewStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
