# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_autoscaling_v2beta2_resource_metric_source import IoK8sApiAutoscalingV2beta2ResourceMetricSource  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiAutoscalingV2beta2ResourceMetricSource(unittest.TestCase):
    """IoK8sApiAutoscalingV2beta2ResourceMetricSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAutoscalingV2beta2ResourceMetricSource(self):
        """Test IoK8sApiAutoscalingV2beta2ResourceMetricSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_autoscaling_v2beta2_resource_metric_source.IoK8sApiAutoscalingV2beta2ResourceMetricSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
