# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_policy_v1beta1_pod_disruption_budget_status import IoK8sApiPolicyV1beta1PodDisruptionBudgetStatus  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiPolicyV1beta1PodDisruptionBudgetStatus(unittest.TestCase):
    """IoK8sApiPolicyV1beta1PodDisruptionBudgetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiPolicyV1beta1PodDisruptionBudgetStatus(self):
        """Test IoK8sApiPolicyV1beta1PodDisruptionBudgetStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_policy_v1beta1_pod_disruption_budget_status.IoK8sApiPolicyV1beta1PodDisruptionBudgetStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
