# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_rbac_v1_subject import IoK8sApiRbacV1Subject  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiRbacV1Subject(unittest.TestCase):
    """IoK8sApiRbacV1Subject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiRbacV1Subject(self):
        """Test IoK8sApiRbacV1Subject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_rbac_v1_subject.IoK8sApiRbacV1Subject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
