# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from api.storage_api import StorageApi  # noqa: E501
from argo.sdk.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = api.storage_api.StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_storage_api_group(self):
        """Test case for get_storage_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
