# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_argoproj_workflow_v1alpha1_http_artifact import IoArgoprojWorkflowV1alpha1HTTPArtifact  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoArgoprojWorkflowV1alpha1HTTPArtifact(unittest.TestCase):
    """IoArgoprojWorkflowV1alpha1HTTPArtifact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoArgoprojWorkflowV1alpha1HTTPArtifact(self):
        """Test IoArgoprojWorkflowV1alpha1HTTPArtifact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_argoproj_workflow_v1alpha1_http_artifact.IoArgoprojWorkflowV1alpha1HTTPArtifact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
