# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_certificates_v1beta1_certificate_signing_request_status import IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiCertificatesV1beta1CertificateSigningRequestStatus(unittest.TestCase):
    """IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCertificatesV1beta1CertificateSigningRequestStatus(self):
        """Test IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_certificates_v1beta1_certificate_signing_request_status.IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
