# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_batch_v2alpha1_cron_job_status import IoK8sApiBatchV2alpha1CronJobStatus  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiBatchV2alpha1CronJobStatus(unittest.TestCase):
    """IoK8sApiBatchV2alpha1CronJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiBatchV2alpha1CronJobStatus(self):
        """Test IoK8sApiBatchV2alpha1CronJobStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_batch_v2alpha1_cron_job_status.IoK8sApiBatchV2alpha1CronJobStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
