# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_coordination_v1_lease import IoK8sApiCoordinationV1Lease  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiCoordinationV1Lease(unittest.TestCase):
    """IoK8sApiCoordinationV1Lease unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoordinationV1Lease(self):
        """Test IoK8sApiCoordinationV1Lease"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_coordination_v1_lease.IoK8sApiCoordinationV1Lease()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
