# coding: utf-8

"""
    Argo API Client

    Generated python client for the Argo Workflows  # noqa: E501

    OpenAPI spec version: v1.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argo.sdk
from models.io_k8s_api_storage_v1beta1_csi_node_spec import IoK8sApiStorageV1beta1CSINodeSpec  # noqa: E501
from argo.sdk.rest import ApiException


class TestIoK8sApiStorageV1beta1CSINodeSpec(unittest.TestCase):
    """IoK8sApiStorageV1beta1CSINodeSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiStorageV1beta1CSINodeSpec(self):
        """Test IoK8sApiStorageV1beta1CSINodeSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argo.sdk.models.io_k8s_api_storage_v1beta1_csi_node_spec.IoK8sApiStorageV1beta1CSINodeSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
